export const GLOBAL_TOGGLE_LEFT_SIDEBAR = "GLOBAL_TOGGLE_LEFT_SIDEBAR" //左侧菜单栏切换
export const GLOBAL_SET_WINDOW_HRIGHT = 'GLOBAL_SET_WINDOW_HRIGHT' //设置窗口高度
export const GLOBAL_SET_USERINFO = 'GLOBAL_SET_USERINFO' // 设置用户信息
export const GLOBAL_SET_UER_MENUS = 'GLOBAL_SET_UER_MENUS' //菜单设置
export const GLOBAL_LOAD_ROUTES_DONE = 'GLOBAL_LOAD_ROUTES_DONE' //加载路由完成