export const GLOBAL_SET_USERINFO = 'GLOBAL_SET_USERINFO' // 设置用户信息
export const GLOBAL_SET_UER_MENUS = 'GLOBAL_SET_UER_MENUS' //菜单设置
export const GLOBAL_LOAD_ROUTES_DONE = 'GLOBAL_LOAD_ROUTES_DONE' //加载路由完成